<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmmanimLagFix.Code\EmmanimLagFix.Code.csproj" />
    <Reference Include="Cosmoteer" Private="true">
      <HintPath>$(CosmoteerBin)\Cosmoteer.dll</HintPath>
    </Reference>
    <Reference Include="HalflingCore" Private="true">
      <HintPath>$(CosmoteerBin)\HalflingCore.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
